#! /bin/bash
# ~/.config/bspwm/bspwmrc by Dr.Deep


# Monitor
bspc monitor -d 1 2 3 4 5 6 7 8 9 10


# Rules
bspc rule -a qalculate-gtk state=floating sticky=on


# Config

## Global
### Color of the border of an unfocused window.
bspc config normal_border_color '#30302f'

### Color of the border of a focused window of an unfocused monitor.
bspc config active_border_color '#474645'

### Color of the border of a focused window of a focused monitor.
bspc config focused_border_color '#817f7f'

### Default split ratio.
bspc config split_ratio 0.52

## Desktop
### Size of the gap that separates windows.
bspc config window_gap 12

## Node
### Window border width.
bspc config border_width 2
